#!/usr/bin/python
##### Methods for authHead+Tail token authentication
# !!!! ALL USER INPUT BEING PASSED TO AUTHSERV MUST BE SANITIZED. DO NOT FORGET.
import sqlite3 as db # PROTOTYPING DB, DO NOT USE IN PRODUCTION, THE KRAKEN WILL COME
import os.path as path
from time import time
import hashlib
from os import urandom

CHALLENGE_AUTH_TIME_SYNC_RANGE = 15 # How much time leeway allowed for challenge auth...
DEFAULT_TOKEN_EXPIRY_LENGTH = 86400 # In seconds, 24h expirt
AuthServerInstance = None

# Auth Token: authHead,authTail,timestamp,challenge
# User Auth: pwdHash,timestamp,challenge
def hashCompute(*args): # Testing hash? Must be same for both client and server.
    netString = ""
    for each in args:
        netString += str(each)

    netString = netString.encode('utf-8')
    hash = hashlib.sha256()
    hash.update(netString)

    return hash.hexdigest()
###

def rngGenHash(): # Salt creation, challenge creation
    return hashCompute(urandom(32))
###

class AuthServ: 
    # Should maintain pub+priv key pair, pub to distribute to servers, priv to decrypt recieved messages... Same priv key for simplicity, distinguish serverOrigin via signing.
    authDb = None
    
    def __init__(this):
        firstRun = not path.isfile("./auth.sqlite")
        this.authDb = db.connect("auth.sqlite")
        this.authDb.execute('PRAGMA foreign_keys = ON') # Needed for cross table checks

        if firstRun: # Setup userDb
            temp = this.authDb.cursor()
            # temp.executescript("""
            #     BEGIN;
            #     CREATE TABLE users(
            #         "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            #         "email" varchar UNIQUE,
            #         "password_hash" varchar,
            #         "username" varchar UNIQUE,
            #         "created_at" timestamp NOT NULL DEFAULT (now()) ?
            #     );
            #     CREATE TABLE tokens(
            #         "authHead" varchar UNIQUE AS PRIMARY KEY,
            #         "authTail" varchar,
            #         "serverScope" varchar,
            #         "id" BIGINT AS FOREIGN KEY REFERENCES users(id),
            #         "expiry" timestamp NOT NULL DEFAULT (now()+36000) ?
            #     );
            #     COMMIT;
            # """)
            temp.execute("CREATE TABLE users(id INTEGER PRIMARY KEY AUTOINCREMENT,email varchar,salt varchar,password_hash varchar,username varchar UNIQUE,created_at timestamp,last_login timestamp)") # Last login for replay attack prevention 
            temp.execute("CREATE TABLE servers(sid INTEGER PRIMARY KEY AUTOINCREMENT,serverPubKey varchar, serverScope varchar UNIQUE)") # Server registry, should be cleared on init? AT LEAST need to maintain an 'authServer' origin used as indexPage tokens
            temp.execute("CREATE TABLE tokens(authHead varchar UNIQUE,authTail varchar UNIQUE,serverScope,id,expiry timestamp,lastCalled timestamp, FOREIGN KEY (serverScope) REFERENCES servers(serverScope), FOREIGN KEY (id) REFERENCES users(id) )")

            temp.execute(f"""INSERT INTO users (id,username,created_at) VALUES (0,"anonymous",{time()})""") # Anonymous user for 'temporary'/unsigned users, only auth tokens allowed, no login thus hash null.
            # temp.execute("""INSERT INTO users (id,email,username) VALUES (0,"none@none.com","admin")""")
            # temp.execute("""INSERT INTO tokens (authHead,authTail,id) VALUES ("abc","def",0)""")
            # temp.execute("""INSERT IGNORE INTO tokens (authHead,authTail) VALUES ("abc1,"def")""")

            # Testing users:
            temp.execute(f"""INSERT INTO users (id,username,created_at,last_login) VALUES (1,"anonymous1",{time()},{time()+1000})""")
            temp.execute(f"""INSERT INTO users (id,username,created_at,last_login,password_hash) VALUES (2,"anonymous2",{time()},{time()-1},"UNHASHED_PASSWORD")""")
            
            # Server auth registry 
            temp.execute(f""" INSERT INTO servers (serverPubKey,serverScope) VALUES ("{"PUBLIC_INDEX_KEY_GOES_HERE"}","indexServer")""") # Use key to validate messages sent by indexServer (eg. adding of servers...). Multiple server ips allowed to correspond to same serverName. Same user could have multiple servers with same pub key.

            this.authDb.commit() # Needed for data written...
    ###

    def userUidAuth(this,uid,timestamps,challenges,results): # In the future, make many challenges. Treating input as 'safe'
        # UID lookup
        userFetch = this.userInfo(uid)
        if not userFetch:
            print(userFetch)
            print("No user found. Not logging in.")
            return False

        # userFetch = this.authDb.cursor().execute(f""" SELECT password_hash,last_login FROM users WHERE id = {uid}""").fetchone() # No sql injection prevention
        # if userFetch is None:
        #     print(userFetch)
        #     print("No user found. Not logging in")
        #     return False

        # Validate timestamp.
        if not isinstance(timestamps,float) or abs(timestamps - time()) >= CHALLENGE_AUTH_TIME_SYNC_RANGE: # Note python processes statements sequentially, ie. early success means math not done on None value...
            print(timestamps)
            print("Timestamp check failed or invalid. Time may be out of sync.")
            return False

        if isinstance(userFetch["last_login"],float) and timestamps <= userFetch["last_login"]: # If lastLogin time exists
            print(timestamps,userFetch["last_login"])
            print("Timestamp check failed. Attempted replay.")
            return False

        # Check challenge string, avoid saving intermediate values to variables...
        # (str(userFetch[0])+str(timestamps)+str(challenges)).encode('utf-8')
        # print((str(userFetch[0])+str(timestamps)+str(challenges)))
        # # hashed = hashlib.sha256().update((str(userFetch[0])+str(timestamps)+str(challenges)).encode('utf-8'))
        # # print(hashed)
        # hash = hashlib.sha256()
        # hash.update((str(userFetch[0])+str(timestamps)+str(challenges)).encode('utf-8'))
        # testResult = hash.hexdigest()

        testResult = hashCompute(userFetch["password_hash"],timestamps,challenges)
        print(testResult)

        if testResult == results:
            print("User auth succeeded...")
            this.authDb.cursor().execute(f""" UPDATE users SET last_login = {time()} WHERE id = {uid} """)
            this.authDb.commit()
            return True

        print("User auth failed.")
        return False
    ###

    def userCreate(this,username,salt,pwdHash,email=None,uid=None): # Assumes password hash was exchanged correctly (secure via pub keys), returns success/fail. Assumes user input sanitized.
        # id BIGINT PRIMARY KEY UNIQUE,email varchar UNIQUE,password_hash varchar,username varchar UNIQUE,created_at timestamp,last_login timestamp

        # Validate username:
        if (this.authDb.cursor().execute(f""" SELECT id FROM users WHERE username = "{username}" """).fetchone()): # if not none, string must have surrounding...
            print("Username already exists.")
            return False

        # Validate uid (for testing):
        if uid and (this.authDb.cursor().execute(f""" SELECT id FROM users WHERE id = {uid} """).fetchone()):
            print("Uid already exists.")
            return False

        ## Create user:
        # this.authDb.cursor().execute(f""" INSERT INTO users  """)
        if uid: 
            this.authDb.cursor().execute(f""" INSERT INTO users (id,email,salt,password_hash,username,created_at) VALUES ({uid},"{email}","{salt}","{pwdHash}","{username}",{time()}) """)
        else:
            this.authDb.cursor().execute(f""" INSERT INTO users (email,salt,password_hash,username,created_at) VALUES ("{email}","{salt}","{pwdHash}","{username}",{time()}) """)

        this.authDb.commit()
        return True
    ###

    def userDelete(this,uid):
        if (this.authDb.cursor().execute(f""" SELECT id FROM users WHERE id = {uid} """).fetchone()):
            this.authDb.cursor().execute(f""" DELETE FROM users WHERE id = {uid} """)
            this.authDb.commit()
            return True
        
        return False
    ###

    def userLookup(this,username=None,email=None): # Return uid(s) array
        if (username): # Note username is unique
            uid = this.authDb.cursor().execute(f""" SELECT id FROM users WHERE username = \"{username}\" """).fetchone()
            if not uid:
                return False
            return [uid]

        if (email): # Note email is NOT NECESSARILY unique, return array
            search = this.authDb.cursor().execute(f""" SELECT id FROM users WHERE email = "{email}" """).fetchall()

            if not search:
                return False
            return search

        return False
    ###

    def userInfo(this,uid): # Return info as dictionary by userId...
        fetch = this.authDb.cursor().execute(f""" SELECT * FROM users WHERE id = {uid} """)

        columns = [description[0] for description in fetch.description]
        rows = fetch.fetchone() # unique id

        if not rows:
            return False

        return dict(zip(columns,rows))
    ###

    def serverAdd(this,servPubKey,servName):
        if (this.authDb.cursor().execute(f""" SELECT serverScope FROM servers WHERE serverScope = "{servName}" """).fetchone()):
            print("Cannot add server, name taken.")
            return False

        this.authDb.cursor().execute(f""" INSERT INTO servers (serverPubKey,serverScope) VALUES ("{servPubKey}","{servName}") """)
        this.authDb.commit()
        return True
    ###

    def userTokenSpawn(this,uid,serverScope,expiry=time()+DEFAULT_TOKEN_EXPIRY_LENGTH):
        # Produce authHead+Tail pair: ie. one sha256 string split...
        authHead = None
        authTail = None

        while(True): # DoWhile
            hash = hashlib.sha256()
            hash.update(urandom(32)) # Sha256 should only produce 32 bytes (256bits)
            authFull = hash.hexdigest()

            authHead = authFull[:32]
            authTail = authFull[32:]

            # print(authFull)
            
            if not (this.authDb.cursor().execute(f""" SELECT authHead FROM tokens WHERE authHead = "{authHead}" """).fetchone()):
                break # If no authHead found, then generated...

        # print("prefail")
        # print(uid)
        this.authDb.cursor().execute(f""" INSERT INTO tokens (authHead,authTail,serverScope,id,expiry) VALUES ("{authHead}","{authTail}","{serverScope}",{uid},{expiry})""")
        # print("postfail")
        this.authDb.commit()

        return [authHead,authTail]
    ###

    def tokenAuth(this,authHead,sourceServer,timestamps,challenges,results,timeRecieveds=time()): # MUST be used in secure connection. Return false or authTail
        target = this.authDb.cursor().execute(f""" SELECT (authTail,serverScope,expiry,lastCalled) FROM tokens WHERE authHead = "{authHead}" """).fetchone()
        # If authHead exists
        if not target:
            print("No such token exists.")
            return False

        # scope matches
        if sourceServer != target[1]:
            print("Scope fail.")
            return False

        # Timestamp resolves
        if abs(timestamps - timeRecieveds) >= CHALLENGE_AUTH_TIME_SYNC_RANGE or timeRecieveds >= target[2]: # Ie. if timestamp out of range of recieve time OR recieved AFTER token expiry.
            print("Timestamp fail or token expired.")
            return False

        # Challange check
        # hash = hashlib.sha256()
        # hash.update((str(authHead)+str(target[0])+str(timestamps)+str(challenges)).encode('utf-8')) # head AND tail used for challenge...
        # testResult = hash.hexdigest()

        testResult = hashCompute(authHead,target[0],timestamps,challenges)

        if testResult == results:
            print("Token auth success.")
            return target[0]

        print("Token tail mismatch")
        return False
    ###
#####

class AuthInterface: # Flask-facing interface, not sanitized
    def __init__(this):
        global AuthServerInstance
        if AuthServerInstance is None: # Global init, bad 'singleton'
            AuthServerInstance = AuthServ()

    # User signup flow
    def signupFirst(this):
        return {"salt":rngGenHash()}

    def signupSecond(this,first,passwordHash,username,email=None): # Final step of signup process, autologin to index server (tokend)
        salt = first["salt"]

        if not AuthServerInstance.userCreate(username,salt,passwordHash,email=email):
            return False # User creation failed.

        # User creation success...
        # print("starting userLookup")
        targetUid = AuthServerInstance.userLookup(username=username)[0][0] # Only one username. Need to double unwrap...
        # print("finished lookup")
        
        return AuthServerInstance.userTokenSpawn(targetUid,"indexServer") # Returns [authHead,authTail], no protection...
    ###

    # User login flow (return indexServer auth token for client)
    def loginFirst(this,username=None,email=None):
        targetUid = AuthServerInstance.userLookup(username=username,email=email)
        if not targetUid:
            return False # User does not exist.

        userInfo = AuthServerInstance.userInfo(targetUid)

        return {"salt":userInfo["salt"],"challenges":rngGenHash(),"uid":targetUid}
    ###

    def loginSecond(this,first,timestamps,results): # Salt not strictly needed...
        # userUidAuth(this,uid,timestamps,challenges,results)
        authResult = AuthServerInstance.userUidAuth(first["uid"],timestamps,first["challenges"],results)

        if not authResult: # False
            print("Login failed.")
            return False

        return AuthServerInstance.userTokenSpawn(first["uid"],"indexServer") # Returns [authHead,authTail], no protection
    ###

    # Token authentication flow (one-step)
    def tokenAuth(this,authHead,sourceServer,timestamps,challenges,results,timeRecieveds=time()):
        # tokenAuth(this,authHead,sourceServer,timestamps,challenges,results,timeRecieveds=time())
        return AuthServerInstance.tokenAuth(authHead,sourceServer,timestamps,challenges,results,timeRecieveds)
    ###
#####

if __name__ == "__main__":
    temp = AuthServ()

    print("DB STATE")
    # print(temp.authDb.cursor().execute("PRAGMA table_info(users);").fetchall())

    print("users:")
    for row in temp.authDb.cursor().execute("SELECT * FROM users"):
        print(row)
    
    print("\ntokens:")
    for row in temp.authDb.cursor().execute("SELECT * FROM tokens"):
        print(row)

    print("\n servers:")
    for row in temp.authDb.cursor().execute("SELECT * FROM servers"):
        print(row)

    temp.userUidAuth(100000,None,None,None)
    temp.userUidAuth(0,None,None,None)
    temp.userUidAuth(0,time()+16,None,None)
    temp.userUidAuth(0,time()-10,None,None)
    temp.userUidAuth(2,None,None,None)
    temp.userUidAuth(1,time()-10,None,None)

    testTime = time()
    hash = hashlib.sha256()
    hash.update(("UNHASHED_PASSWORD"+str(testTime)+"test").encode('utf-8'))
    temp.userUidAuth(2,testTime,"test",hash.hexdigest())
    temp.userUidAuth(2,testTime,"test",hash.hexdigest()) # Should fail due to replay attack...
    temp.userUidAuth(2,testTime+1,"test",hash.hexdigest()) # Should fail due to replay attack...
    temp.userUidAuth(2,testTime+15,"test",hash.hexdigest()) # Should fail due to replay attack...
    temp.userUidAuth(2,testTime-15,"test",hash.hexdigest()) # Should fail due to replay attack...

    testTime = time()+10
    hash = hashlib.sha256()
    hash.update(("UNHASHED_PASSWORD"+str(testTime)+"test").encode('utf-8')) # Note result of challenges MUST be calculated same way...
    temp.userUidAuth(2,testTime,"test",hash.hexdigest())

    temp.userCreate("anon",None,None)
    temp.userCreate("anon",None,None,uid=3)

    temp.userCreate("testUser",None,None)

    temp.userCreate("anon2",None,None,uid=10)


    # temp.userTokenSpawn(100,"indexServer1") # FAILS, USER FOREIGN KEY ENFORCEMENT
    # temp.userTokenSpawn(0,"test") # FAILS, SERVER ENFORCEMENT
    testFull = temp.userTokenSpawn(0,"indexServer") # Works, spawns token-based keys from 

    # ... (Test api access)
    test2 = AuthInterface()