#!/usr/bin/python
##### Methods for authHead+Tail token authentication
# !!!! ALL USER INPUT BEING PASSED TO AUTHSERV MUST BE SANITIZED. DO NOT FORGET.
import sqlite3 as db # PROTOTYPING DB, DO NOT USE IN PRODUCTION, THE KRAKEN WILL COME
import os.path as path
from time import time
import hashlib
from os import urandom

CHALLENGE_AUTH_TIME_SYNC_RANGE = 15 # How much time leeway allowed for challenge auth...
DEFAULT_TOKEN_EXPIRY_LENGTH = 86400 # In seconds?

class AuthServ: 
    # Should maintain pub+priv key pair, pub to distribute to servers, priv to decrypt recieved messages... Same priv key for simplicity, distinguish serverOrigin via signing.
    authDb = None
    
    def __init__(this):
        firstRun = not path.isfile("./auth.sqlite")
        this.authDb = db.connect("auth.sqlite")
        this.authDb.execute('PRAGMA foreign_keys = ON') # Needed for cross table checks

        if firstRun: # Setup userDb
            temp = this.authDb.cursor()
            # temp.executescript("""
            #     BEGIN;
            #     CREATE TABLE users(
            #         "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            #         "email" varchar UNIQUE,
            #         "password_hash" varchar,
            #         "username" varchar UNIQUE,
            #         "created_at" timestamp NOT NULL DEFAULT (now()) ?
            #     );
            #     CREATE TABLE tokens(
            #         "authHead" varchar UNIQUE AS PRIMARY KEY,
            #         "authTail" varchar,
            #         "serverScope" varchar,
            #         "id" BIGINT AS FOREIGN KEY REFERENCES users(id),
            #         "expiry" timestamp NOT NULL DEFAULT (now()+36000) ?
            #     );
            #     COMMIT;
            # """)
            temp.execute("CREATE TABLE users(id INTEGER PRIMARY KEY AUTOINCREMENT,email varchar,salt varchar,password_hash varchar,username varchar UNIQUE,created_at timestamp,last_login timestamp)") # Last login for replay attack prevention 
            temp.execute("CREATE TABLE servers(sid INTEGER PRIMARY KEY AUTOINCREMENT,serverPubKey varchar, serverScope varchar UNIQUE)") # Server registry, should be cleared on init? AT LEAST need to maintain an 'authServer' origin used as indexPage tokens
            temp.execute("CREATE TABLE tokens(authHead varchar UNIQUE,authTail varchar UNIQUE,serverScope,id,expiry timestamp, FOREIGN KEY (serverScope) REFERENCES servers(serverScope), FOREIGN KEY (id) REFERENCES users(id) )")

            temp.execute(f"""INSERT INTO users (id,username,created_at) VALUES (0,"anonymous",{time()})""") # Anonymous user for 'temporary'/unsigned users, only auth tokens allowed, no login thus hash null.
            # temp.execute("""INSERT INTO users (id,email,username) VALUES (0,"none@none.com","admin")""")
            # temp.execute("""INSERT INTO tokens (authHead,authTail,id) VALUES ("abc","def",0)""")
            # temp.execute("""INSERT IGNORE INTO tokens (authHead,authTail) VALUES ("abc1,"def")""")

            # Testing users:
            temp.execute(f"""INSERT INTO users (id,username,created_at,last_login) VALUES (1,"anonymous1",{time()},{time()+1000})""")
            temp.execute(f"""INSERT INTO users (id,username,created_at,last_login,password_hash) VALUES (2,"anonymous2",{time()},{time()-1},"UNHASHED_PASSWORD")""")
            
            # Server auth registry 
            temp.execute(f""" INSERT INTO servers (serverPubKey,serverScope) VALUES ("{"PUBLIC_INDEX_KEY_GOES_HERE"}","indexServer")""") # Use key to validate messages sent by indexServer (eg. adding of servers...). Multiple server ips allowed to correspond to same serverName. Same user could have multiple servers with same pub key.

            this.authDb.commit() # Needed for data written...
    ###

    def userUidAuth(this,uid,timestamps,challenges,results): # In the future, make many challenges. Treating input as 'safe'
        # UID lookup
        userFetch = this.authDb.cursor().execute(f""" SELECT password_hash,last_login FROM users WHERE id = {uid}""").fetchone() # No sql injection prevention
        if userFetch is None:
            print(userFetch)
            print("No user found. Not logging in")
            return False

        # Validate timestamp.
        if not isinstance(timestamps,float) or abs(timestamps - time()) >= CHALLENGE_AUTH_TIME_SYNC_RANGE: # Note python processes statements sequentially, ie. early success means math not done on None value...
            print(timestamps)
            print("Timestamp check failed or invalid. Time may be out of sync.")
            return False

        if isinstance(userFetch[1],float) and timestamps <= userFetch[1]: # If lastLogin time exists
            print(timestamps,userFetch[1])
            print("Timestamp check failed. Attempted replay.")
            return False

        # Check challenge string, avoid saving intermediate values to variables...
        # (str(userFetch[0])+str(timestamps)+str(challenges)).encode('utf-8')
        print((str(userFetch[0])+str(timestamps)+str(challenges)))
        # hashed = hashlib.sha256().update((str(userFetch[0])+str(timestamps)+str(challenges)).encode('utf-8'))
        # print(hashed)
        hash = hashlib.sha256()
        hash.update((str(userFetch[0])+str(timestamps)+str(challenges)).encode('utf-8'))
        testResult = hash.hexdigest()
        print(testResult)

        if testResult == results:
            print("User auth succeeded...")
            this.authDb.cursor().execute(f""" UPDATE users SET last_login = {time()} WHERE id = {uid} """)
            this.authDb.commit()
            return True

        print("User auth failed.")
        return False
    ###

    def userCreate(this,username,salt,pwdHash,email=None,uid=None): # Assumes password hash was exchanged correctly (secure via pub keys), returns success/fail. Assumes user input sanitized.
        # id BIGINT PRIMARY KEY UNIQUE,email varchar UNIQUE,password_hash varchar,username varchar UNIQUE,created_at timestamp,last_login timestamp

        # Validate username:
        if (this.authDb.cursor().execute(f""" SELECT id FROM users WHERE username = "{username}" """).fetchone()): # if not none, string must have surrounding...
            print("Username already exists.")
            return False

        # Validate uid (for testing):
        if uid and (this.authDb.cursor().execute(f""" SELECT id FROM users WHERE id = {uid} """).fetchone()):
            print("Uid already exists.")
            return False

        ## Create user:
        # this.authDb.cursor().execute(f""" INSERT INTO users  """)
        if uid: 
            this.authDb.cursor().execute(f""" INSERT INTO users (id,email,salt,password_hash,username,created_at) VALUES ({uid},"{email}","{salt}","{pwdHash}","{username}",{time()}) """)
        else:
            this.authDb.cursor().execute(f""" INSERT INTO users (email,salt,password_hash,username,created_at) VALUES ("{email}","{salt}","{pwdHash}","{username}",{time()}) """)

        this.authDb.commit()
        return True
    ###

    def serverAdd(this,servPubKey,servName):
        if (this.authDb.cursor().execute(f""" SELECT serverScope FROM servers WHERE serverScope = "{servName}" """).fetchone()):
            print("Cannot add server, name taken.")
            return False

        this.authDb.cursor().execute(f""" INSERT INTO servers (serverPubKey,serverScope) VALUES ("{servPubKey}","{servName}") """)
        this.authDb.commit()
        return True
    ###

    def userTokenSpawn(this,uid,serverScope,expiry=time()+DEFAULT_TOKEN_EXPIRY_LENGTH):
        # Produce authHead+Tail pair: ie. one sha256 string split...
        authHead = None
        authTail = None

        while(True): # DoWhile
            hash = hashlib.sha256()
            hash.update(urandom(32)) # Sha256 should only produce 32 bytes (256bits)
            authFull = hash.hexdigest()

            authHead = authFull[:32]
            authTail = authFull[32:]

            print(authFull)
            
            if not (this.authDb.cursor().execute(f""" SELECT authHead FROM tokens WHERE authHead = "{authHead}" """).fetchone()):
                break # If no authHead found, then generated...

        this.authDb.cursor().execute(f""" INSERT INTO tokens (authHead,authTail,serverScope,id,expiry) VALUES ("{authHead}","{authTail}","{serverScope}",{uid},{expiry})""")
        this.authDb.commit()

        return [authHead,authTail]
    ###
#####

if __name__ == "__main__":
    temp = AuthServ()

    print("DB STATE")
    # print(temp.authDb.cursor().execute("PRAGMA table_info(users);").fetchall())

    print("users:")
    for row in temp.authDb.cursor().execute("SELECT * FROM users"):
        print(row)
    
    print("\ntokens:")
    for row in temp.authDb.cursor().execute("SELECT * FROM tokens"):
        print(row)

    print("\n servers:")
    for row in temp.authDb.cursor().execute("SELECT * FROM servers"):
        print(row)

    temp.userUidAuth(0,None,None,None)
    temp.userUidAuth(0,time()+16,None,None)
    temp.userUidAuth(0,time()-10,None,None)
    temp.userUidAuth(2,None,None,None)
    temp.userUidAuth(1,time()-10,None,None)

    testTime = time()
    hash = hashlib.sha256()
    hash.update(("UNHASHED_PASSWORD"+str(testTime)+"test").encode('utf-8'))
    temp.userUidAuth(2,testTime,"test",hash.hexdigest())
    temp.userUidAuth(2,testTime,"test",hash.hexdigest()) # Should fail due to replay attack...
    temp.userUidAuth(2,testTime+1,"test",hash.hexdigest()) # Should fail due to replay attack...
    temp.userUidAuth(2,testTime+15,"test",hash.hexdigest()) # Should fail due to replay attack...
    temp.userUidAuth(2,testTime-15,"test",hash.hexdigest()) # Should fail due to replay attack...

    testTime = time()+10
    hash = hashlib.sha256()
    hash.update(("UNHASHED_PASSWORD"+str(testTime)+"test").encode('utf-8')) # Note result of challenges MUST be calculated same way...
    temp.userUidAuth(2,testTime,"test",hash.hexdigest())

    temp.userCreate("anon",None,None)
    temp.userCreate("anon",None,None,uid=3)

    temp.userCreate("testUser",None,None)

    temp.userCreate("anon2",None,None,uid=10)


    # temp.userTokenSpawn(100,"indexServer1") # FAILS, USER FOREIGN KEY ENFORCEMENT
    # temp.userTokenSpawn(0,"test") # FAILS, SERVER ENFORCEMENT
    temp.userTokenSpawn(0,"indexServer") # Works, spawns token-based keys from 