-- psql -U extsearch -d extsearch_auth -f auth_server/db/schema.sql
-- Authentication Database Schema
-- This database is owned by the auth server and stores user accounts only.
-- All other data (submissions, workspaces, etc.) lives in the submissions DB.

CREATE TABLE "users" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar UNIQUE,
  "username" varchar UNIQUE,
  "display_name" varchar,
  "password_hash" varchar,
  "created_at" timestamp NOT NULL DEFAULT (now())
);
